### PR TITLE
Removing validate_keys_none

### PR DESCRIPTION
**Pull request by mottosso**
Let me know what you think of this.

Basically, keys are excluded on export, instead of validated against.

### CODE REVIEW

**Comment by mottosso** [comment]
About validation of history, here's my line of thinking.

When working on a model, history can be useful, especially when working with deformers or modifiers where the options may be changed, such as subdivision or split-edge count.

So the idea is to allow for this in the development scene, whilst still keeping the published file clean.

**Result**

image

**Development file**

image

**Comment by mottosso** [comment]
And the reason for changing the construction history validator, was because it included additional nodes on it's own that would otherwise _not_ have been exported, because they were not part of the instance. So really it was crying wolf.

I figured anything that _isn't_ a DAG node to be classifiable as history, but maybe it's too harsh. Didn't get far into testing it until I realised the above.

**Comment by BigRoy** [comment]
Removing the `validate_keys_none` I think is tricky. This has been raised before, but this Validator was less about avoiding it being included in the Extraction but more about warning the artist that his scene has keys. 

If Extraction would happen on a different frame the output would be different.

Or we would Validate that the scene is on frame 1, which might be a more confusing invalidation (as to why that is important for extraction) than warning them about keys? I don't think any artist would come up with why exporting on frame 1 is a requirement.

**Comment by mottosso** [comment]
> Or we would Validate that the scene is on frame 1

Could do. But they might still have keyframes causing non-zero values on frame 1. How about validating that every node has zero transforms?

**Comment by BigRoy** [comment]
> Could do. But they might still have keyframes causing non-zero values on frame 1. How about validating that every node has zero transforms?

The construction history could have keys, so it wouldn't show as an issue. Or transforms not included in the extraction but part of the history chain wouldn't be caught either.

> How about validating that every node has zero transforms?

This should be already in there. See: https://github.com/pyblish/pyblish-magenta/blob/master/pyblish_magenta/plugins/validate_transform_frozen.py

Looking at that code reminds me. Are we Validating that only transforms, meshes, curves are in the instance? If so, then your changed construction history validator wouldn't have been needed either. ;)

---

Preferrably I would have two Validators raise an error for a _similar thing_ where in some cases they wouldn't collide. In short, Validators could sometimes overlap. All we want in the end is that the Validation is as clear as possible to the Artist. 

For example, your construction history Validator wouldn't pass if an animCurve was found in the instance, but I'd still warn the artist separately that he has keys in the scene that could possibly influence his output. (Of course if we decide this is an appropriate warning)

**Comment by mottosso** [comment]
> This should be already in there

Ah, I think that solves it then.

**Comment by mottosso** [comment]
> Or transforms not included in the extraction but part of the history chain wouldn't be caught either.

Just a note on this; transforms of shapes are guaranteed to be included because of how we use the `preview` of `cmds.file`. It can't export shapes without their transforms.

**Comment by BigRoy** [comment]
> Just a note on this; transforms of shapes are guaranteed to be included because of how we use the preview of cmds.file. It can't export shapes without their transforms.

You misunderstood. Imagine doing a `combine` of two meshes with construction history. The newly created mesh is included in the extraction (with its transform), but of course the history isn't. Those two transforms of the original meshes would still exist and could be keyed.

Similarly a polyExtrude node could have keys on its attributes.
Maybe set up a separate issue for this complex case?

Or course it'll be hard to check for everything. But these things unfortunately seem to happen. If the Validators can remain clear to the artist I would say it's great these 0.1% chance cases get caught. It's especially those cases that don't happen often that are mostly missed when something goes wrong. They take longest to track down because you don't immediately think of it.

**Comment by mottosso** [comment]
> Those two transforms of the original meshes would still exist and could be keyed.

Ah, ok I see, that's a good point.

How about we start by finding the problem, encapsulate it in a scene we can test against, and work our way towards a good solution from there? It does sound like a tricky problem, but I think the gain of having your development scene remain flexible is worth fighting for.

**Comment by mottosso** [comment]
> Note that this would allow cameras and locators in the output. Do we want that?

It would have to be explicitly added to the output assembly for this to happen, but I think you're right, this should probably be prohibited..

**Comment by mottosso** [comment]
Have you ever thought about outputting as `obj` instead?

**Comment by BigRoy** [comment]
> Have you ever thought about outputting as obj instead?

I have yes. But unfortunately I haven't had great experiences with `.obj` in the past. Sometimes it merged objects/groups. But could've been applications like Zbrush doing strange things with it. There's likely a lot of settings for `.obj` that could be set to make it work more as expected.

**Comment by mottosso** [comment]
An `obj` might not include hierarchy?

**Comment by BigRoy** [comment]
> An obj might not include hierarchy?

Not sure. Don't have too much experience with it.
Another thing what keeps me reluctant to use the format because it seems to grow a bit outdated. Would it support openSubdiv? Or does it support the _creases_ we're using in _The Deal_ currently.

What would be the gain?

**Comment by mottosso** [comment]
No I think you're right, there will be mesh settings it won't accommodate for.

The gain would be a stronger guarantee of what's inside; i.e. only meshes. Less surprises. But also portability; opening the model in Fusion for example.

How about Alembic? It would save us from worrying about history, and maintain portability.

**Comment by BigRoy** [comment]
> How about Alembic? It would save us from worrying about history, and maintain portability.

Could be a good option. Especially since we're also exporting our assets in a cached manner from animation with Alembic. Whatever data we lose from modeling would just as well get lost from animation. This means we would lose it sooner which is often a good thing, so any issues are caught earlier.

This would also avoid the shader export issue. And it allows us to exclude the children hierarchies (which it does by default). _tokejepsen_'s referencing issue of having to have the plug-in loaded otherwise the reference would just get skipped is something to look out for whenever we would start referencing the alembic though.

Actually, thinking about it. Even more so we could make a mayaAscii file similar like we do with animation. Basically importing the Alembic and exporting the mesh. So we would output both `.ma` and `.abc` from modeling? (We used to do that too) By using the Alembic to create the `.ma` ensures the contents are the same.

**Comment by mottosso** [comment]
Ok, models now forbid anything but meshes during publish, allows construction history but does not publish it.

Animated construction history is still an issue; ideally I would look the problem straight in the eye before trying to validate against it.

**Comment by mottosso** [comment]
> Could we leave this explanation in there.

Yes, sorry, forgot to put that back in.

I meant to put it in another docstring, as it isn't relevant to artist, but may be relevant to the developer.

**Comment by mottosso** [comment]
> Artists in our studio actually know 'freeze transform' better than 'zero transforms'

Yeah, but isn't "freeze transforms" is a way of _achieving_ "zero transforms"? We could add these type of instructions to the docstring. At the moment, freeze transforms suggests you will need to run this command before publishing.

**Comment by mottosso** [comment]
Merging and moving on.

**Pull request merged**
