### PR TITLE
Implemented basic versioning

### PR DESCRIPTION
**Pull request by mottosso**
Key points here are:
1. Each extractor now extracts to a particular format, as opposed to a particular family. Before an extractor was `extract_model`, now it is `extract_maya_ascii`
2. Each extractor creates it's own temporary directory, which is finally cleaned up during `integrate_cleanup.py` with an order of 99
3. Versioning is handled last, during integration.
4. No more collect_instance_data
5. No more integrate_increment_version
6. Integration directory is now based on `TASK` as opposed  to `family`, allowing multiple families coming out of a single task.

Each publish produces a unique directory per version under `/publish/v001`.

### CODE REVIEW

**Comment by mottosso** [comment]
Added rig collector and extractor.

The rig uses the same extractor for ASCII output, quicktime and GIF as the model.

**Comment by BigRoy** [comment]
> The rig uses the same extractor for ASCII output, quicktime and GIF as the model.

Extracting a rig with `constructionHistory = False` will likely break it. :)

**Comment by mottosso** [comment]
> Extracting a rig with `constructionHistory = False` will likely break it. :)

Ok, this is the part I don't think you're quite following me on, and I don't blame you, so I'll try and show you how this actually does work for rigs as well on the forums.

**Comment by BigRoy** [comment]
Cool, will have a look shortly! And thanks.

**Comment by mottosso** [comment]
Merging and moving on

**Pull request merged**
