### PR TITLE
Implement label for Plug-ins and versioning for Integrators

### PR DESCRIPTION
**Pull request by BigRoy**
- Labeled most of the Plug-ins so the name is more readable in the GUI
- Some extra separation of logic in the Collectors to allow for separation in Integration
- Versioning implemented for Integrators.

### CODE REVIEW

**Comment by mottosso** [comment]
Sweet beans!

**Comment by mottosso** [comment]
``` python
        def get_all_parents(long_name):
            parents = long_name.split("|")[1:-1]
            return ['|{0}'.format('|'.join(parents[0:i+1]))
                    for i in xrange(len(parents))]
```

What is the reasoning behind this one? Wouldn't it do with a `cmds.listRelatives(shape, parent=True)` as they are guaranteed to be shapes, and shapes must have at least one parent?

**Comment by BigRoy** [comment]
It's getting **all** parents and not only the current one. So it's returning a list of nodes instead of only the current parent. 

Also since we already have the long name in this instance it's an optimization to get it from the name as opposed to doing a Maya call (or a series of Maya calls to get all parents). This is much faster.

**Comment by mottosso** [comment]
Ah, ok, that makes sense.

**Comment by BigRoy** [comment]
That's because all parent nodes are important for validation, since they are included in Extraction. :) So I'm ensuring they are all included as separate nodes.

**Comment by mottosso** [comment]
Yes, you are absolutely right. :)

**Pull request merged**
