### PR TITLE
Test

### PR DESCRIPTION
**Pull request by mottosso**

### CODE REVIEW

**Comment by mottosso** [comment]
Looking good so far.

The goal of this is to have GitHub run tests automatically in an environment where Maya is available. The "All checks have passed" will be an indication of that, and the "details" button next to it will link to the output following running the test.

**Comment by BigRoy** [comment]
> The goal of this is to have GitHub run tests automatically in an environment where Maya is available. The "All checks have passed" will be an indication of that, and the "details" button next to it will link to the output following running the test.

Sweet, haven't worked with something like that before and am looking forward to learning the ins- and outs!

**Comment by mottosso** [comment]
The idea is simply to create a series of tests for features of Magenta, and have those run upon each pull-request. That way, anyone can PR, and tests will always run, regardless of whether you have all versions of Maya installed that Magenta is meant to support. And regardless of whether or not you are familiar with how to run tests to begin with.

If we already had that, I would have - for example - seen immediately that by removing the use of `exporter.py` and reverting to `cmds.file` I would have broken X and Y. And the pull-request would look red, and provide a trace of the tests.

**Comment by BigRoy** [comment]
So how exactly does it run in the environment with Maya available? Does it run locally, and how?

**Comment by mottosso** [comment]
That's where the magic happens. :)
1. Whenever a pull-request is made or is updated, GitHub sends a POST request to a pre-defined address
2. At this address, my web application is running to receive the request
3. Upon receiving the request, a new virtual machine is started (via Docker)
4. In this virtual machine, the repository is pulled
5. Once pulled, `nosetests` is run, which traverses the repo to look for tests (as usual)
6. Once finished, the output is sent back out to the web application
7. The web application publishes the results to the address at the `details` button here on GitHub.
8. Along with a "success" or "failed" message, which will determine whether GitHub should warn about the current pull request.

The idea is to offer a configuration file for the tests, such that you can customise the environment in which the pull requests are run, and exactly what commands are run, similar to how Travis does it.

Here's the Pyblish configuration, it runs on both Python 2.6 and Python 2.7.

I want that, but for Maya 2012+, and also for other software. Anything where automated tests for Pyblish is useful. Solving the issue of testing with DCC apps once and for all.

(I'm also considering making something like this a paid service, depending on how large the audience turns out to be)

**Comment by mottosso** [comment]
Forgot the link to the Travis file.
- https://github.com/pyblish/pyblish/blob/master/.travis.yml

**Comment by BigRoy** [comment]
Thanks for the explanation, and that's really cool!

Let's get this party started.

**Comment by mottosso** [comment]
Really cool! It was surprisingly straightforward to set up, curious no one has done it before.

**Comment by BigRoy** [comment]
Ooh, exciting!

**Comment by mottosso** [comment]
Allright, working well :) Hit "details" to see how tests went.

I'll be away for a day or two, and since this is running locally it'll be down until I return. But this works perfectly and has much potential. Currently works with Maya 2015 SP5 only, but I'll be adding in all maya's, and other hosts too, especially Nuke and Houdini, and their corresponding versions.

**Comment by mottosso** [comment]
Adding screenshot for reference, logging off now.

image

**Comment by BigRoy** [comment]
Ah that's looking great! Is it possible to run the tests locally 'hassle-free' as well if you have the correct software installed? 

I assume the online testing is used solely for the commits/pushes onto Github and the pull requests. But it would be great to get started locally already (or when services would be down)!

Other than that it's great you took the time to look into this!
And... since it's passing at the moment, should we already merge the pull request?

**Comment by mottosso** [comment]
> Is it possible to run the tests locally 'hassle-free' as well if you have the correct software installed?

Certainly, just run `mayapy run_testsuite.py`. You'll need nose installed. Make it a habit to always run this whenever you make a change. The more often, the smaller the errors and the easier they are to fix.

Ideally the Github tests should always pass, it's when we start testing against multiple maya's that it gets more difficult to do and remember to do locally.

> And... since it's passing at the moment, should we already merge the pull request?

Sure! Try making a test of your own too, the goal is to have each plugin tested in at least one circumstance. A total stranger should be able to pull request without accidentally breaking anything.

**Pull request merged**
