### PR TITLE
Simplifying model selector

### PR DESCRIPTION
**Pull request by mottosso**
Three major things were done here.
1. No more `collect_assets`
2. No more dependency on ordering
3. Accurate collection of nodes relevant to a publish via `cmds.file`

Might have stepped on the toes of other plug-ins, let's talk about that, specifically have a look at `collect_model`.

### CODE REVIEW

**Comment by BigRoy** [comment]
There's a couple of possible problematic points here.

> 1 No more `collect_assets`

This would mean `collect_model` is only for this pipeline, it won't be usable for another. Basically I was thinking about having each collector be responsible for as little as possible. This way we can make a new pipeline by dropping in another mixture of collectors. At best case scenario the processing method of `collect_model` would solely collect the models in a scene based on previously captured that.

The next topic would be the direct querying of information from the environment. I think that's _pipeline dependent_. Might make more sense to have separation for that as well so the collector solely uses the data from the context and instances as much as possible? All we need to do to make it work in another pipeline is build the minimalistic `Collector` that provides that data from their pipeline for this collector.

Also grabbing the data inside the model collector would mean duplicity of code in each Collector. Similar data is acquired for Rigging, LookDev, Animation, etcetera. What do you think?

> 3 Accurate collection of nodes relevant to a publish via cmds.file

We don't know what settings will be used for Extraction. I think the `Collector` should only collect nodes that are related to what we're trying to Collect. I think currently it's collecting history, connections, channels, expressions, etc. A model brings only a hierarchy and shapes. Can we set up the cmds.file command so that it only lists this relevant nodes?

This also brings us back to another discussion we had about Inclusive vs Exclusive (or actually subtractive vs additive) #1. For example an empty group within the hierarchy (null group) doesn't provide any Model information. We can skip it during Collection and need to ensure during Extraction that it won't be exported, thus we are Exclusive about this data. Or we include it and just Validate that empty groups are not allowed. (I think by default `cmds.file` will export including children? Thus inclusive.) What would we as developers prefer, or even better... what would the artist prefer?

Do we want to just skip it in the output, or do we want to _stop_ the artist and don't allow the output without him requiring the remove the empty null groups.

To get the full context of this discussion you should note that empty groups could be relevant to the modeler (eg. for construction history) so that he can continue working on the model easily. They are just not relevant to his published output. The same goes for construction history. Currently we're validating that there is no construction history, but we could also just be Exclusive about construction history and don't care whether the modeler has it in his scene (which is likely convenient for him). We'll just publish without it.

**Comment by mottosso** [comment]
> This would mean collect_model is only for this pipeline, it won't be usable for another.

What does you mean, it would be valid anywhere `ITEM` and `TASK` is set.

At this point, it is independent of both file-system and software, this wasn't the case before. We use `be` to set these variables, but any environment management application will do, including Shotgun and FTrack. I'd say this is _more_ flexible than before, not less?

**Comment by mottosso** [comment]
> I think the Collector should only collect nodes that are related to what we're trying to Collect

Agreed, I've pushed an update for this.

Before, nodes were added directly, they are now added "indirectly". It hooks into Maya's dependency resolution to find nodes only related to `ben_GRP` - which means there may be other nodes outside of Ben that won't be processed, and won't cause issues with validators either.

``` python
# Capture nodes relevant to the model
with pyblish_maya.maintained_selection():
    cmds.select(assembly)
    nodes = cmds.file(exportSelected=True,
                      preview=True,
                      constructionHistory=True,
                      force=True)

# Reduce to relevant nodes
shapes = cmds.ls(nodes,
                 noIntermediate=True,
                 shapes=True,
                 long=True,
                 dag=True)
```

**Comment by mottosso** [comment]
Actually, let's have these conversations on the forum, I think it makes more sense as otherwise information gets spread out. Lots of good thoughts in here already.
- http://forums.pyblish.com/t/pyblish-magenta/79/185

**Comment by BigRoy** [comment]
Great, let's get this linked on the forums!

``` python
# Capture nodes relevant to the model
with pyblish_maya.maintained_selection():
    cmds.select(assembly)
    nodes = cmds.file(exportSelected=True,
                      preview=True,
                      constructionHistory=True,
                      force=True)

# Reduce to relevant nodes
shapes = cmds.ls(nodes,
                 noIntermediate=True,
                 shapes=True,
                 long=True,
                 dag=True)
```

Note that this would reduce dependency on the hierarchy, which I assume is relevant from a model as output. Unless one assumes a flat hierarchy (shapes next to each other) is the preferred output.

What you're doing here is close to the code that was there. Though in the code in earlier commits it was also including all parents of the shapes to ensure the entire hierarchy is included in the instance and can be validated as such. ;)

**Comment by mottosso** [comment]
Ah, I see. But there is one major difference, I'm typing this up on the forums now.

**Comment by mottosso** [comment]
Merging and moving on to next topic.

**Pull request merged**
