### PR TITLE
Updating .pyblish configuration

### PR DESCRIPTION
**Pull request by mottosso**
Added support for loads of Maya versions.
- https://github.com/mottosso/docker-maya

See branches!

### CODE REVIEW

**Comment by mottosso** [comment]
Merging this so we can move on, the tests don't actually fail, there's just a bad internet connection here (running locally).

**Comment by mottosso** [comment]
This is the one to talk about.
- [test_model.py](https://github.com/pyblish/pyblish-magenta/blob/ba658c67cc4b6cc684f98db89bfba4b54699f3aa/pyblish_magenta/tests/test_model.py)

The technique is essentially this; (1) import a plug-in, (2) register it in isolation (with `registered()`) alongside any of it's dependencies, such as `CollectModel`, and (3) runs the native `pyblish.util.publish()` function.

There were a few reasons for this as opposed to calling `process()` on a plug-in by hand
1. Filters "hosts" and "families" are ignored
2. In case of dependent plug-ins, "order" is ignored
3. LOC reduced, with the context manager `with registered("MyPlugin")`
4. Argument signature may change, e.g. from `(context)` to `(context, instance)`, breaking a test
5. Both name of plug-in and name of file must be known during tests, making change difficult
6. Actual `results` are produced and can be evaluated; these are the same results as those present in the GUI

Tests now look like this.

``` python
with registered("CollectModel", "ValidateSomething"):
  context = pyblish.util.publish()
```

**Comment by mottosso** [comment]
And perhaps the more important thing, tests now output a lot more interesting information, including the actual error message, but also print-statements. So it's a bit easier to debug things.

``` bash
marcus@ALIENFX>mayapy run_tests.py
======================================================================
FAIL: Collecting clean model works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Files\Autodesk\Maya2015\Python\lib\site-packages\nose\case.py", line 19
7, in runTest
    self.test(*self.arg)
  File "C:\Users\marcus\test\tests\test_something.py", line 49, in test_collection
    assert "ben" in context, context
AssertionError: [pyblish.plugin.Instance("ben")]
-------------------- >> begin captured stdout << ---------------------
Fetching plug-in from module..
Running plug-in..
Evaluating results..
--------------------- >> end captured stdout << ----------------------
----------------------------------------------------------------------
Ran 1 test in 0.032s

FAILED (failures=1)
```

**Comment by BigRoy** [comment]
Looking really good. Those utilities for testing like `registered ()` and `errored ()`, do you think they would fit nicely into pyblish itself? 

Or maybe a pyblish-tests package that simplifies the implementation of tests for anyone doing tests for their plug-ins.

I think in `pyblish` itself could be a great fit, setting a standard for testing pyblish plug-ins, even integrations could do it!

---

Other than that I think the context manager `registered ()` should error out if it can't find the plug-in by id as opposed to continuing without it.

What do you think?

**Comment by mottosso** [comment]
> Those utilities for testing like registered () and errored (), do you think they would fit nicely into pyblish itself?

Possibly, yes. Time will have to tell whether they last or not, it's really just a first attempt at getting a convenient handle on how to test plug-ins. I wouldn't be surprised if we find something even better soon.

> Other than that I think the context manager registered () should error out if it can't find the plug-in by id as opposed to continuing without it.

That's a good idea.

**Pull request merged**
