### PR TITLE
Extraction of lookdev shaders and links as JSON

### PR DESCRIPTION
**Pull request by mottosso**
Here's what the JSON looks like.

``` json
{
    "lightMetal_SHD": [
        "|:ben_GRP|:head_GEO"
    ], 
    "orangeMetal_SHD": [
        "|:ben_GRP|:body_GEO"
    ], 
    "darkMetal_SHD": [
        "|:ben_GRP|:L_arm_GEO", 
        "|:ben_GRP|:R_arm_GEO", 
        "|:ben_GRP|:neck_GEO", 
        "|:ben_GRP|:L_leg_GEO", 
        "|:ben_GRP|:R_leg_GEO"
    ]
}
```

Here's some code to connect shaders with their meshes.

``` python
import json

fname = r"C:\Users\marcus\Dropbox\Pyblish\thedeal\assets\ben\lookdev\publish\v008\lookdev\ben\thedeal_ben_lookdev_ben_v008.json"
with open(fname) as f:
    links = json.load(f)

for shader, meshes in links.iteritems():
    shader = "lookdev_:" + shader
    shading_group = cmds.sets(name=shader + "ShadingGroup",
                              renderable=True,
                              noSurfaceShader=True,
                              empty=True)
    cmds.connectAttr(shader + ".outColor",
                     shading_group + ".surfaceShader",
                     force=True)
    cmds.sets(meshes, edit=True, forceElement=shading_group)
```

### CODE REVIEW

**Comment by mottosso** [comment]
Next iteration will involve transforming the above dictionary to something like this.

``` json
{
    "f7b112ad-90bf-4274-8329-19a02092a083": [
        "f7d26333-588a-417d-bdb0-edf9d27cc491"
    ], 
    "53470dac-3709-499d-a490-4b8003b178ee": [
        "f67f7d00-29c9-4948-ac39-05afbb32a145"
    ], 
    "f7d26333-588a-417d-bdb0-edf9d27cc491": [
        "8048064a-f6e0-48d4-bd03-e45b13dd2526", 
        "53470dac-3709-499d-a490-4b8003b178ee", 
        "f67f7d00-29c9-4948-ac39-05afbb32a145"
    ]
}
```

Where each _UUID_ is a unique reference to a node anywhere, not just in the scene, but globally, everywhere in the world, in every scene that exists or will ever exist. :)

This is to avoid hierarchies and interpolation, as hierarchy play no part in the shading itself.

**Comment by mottosso** [comment]
And about the workflow, here's what the lookdev artists is to do in order to publish his work.
1. Look dev
2. Store all relevant meshes in a `assigned_SET` objectSet.
3. Publish

Shaders are determined by the meshes in that set.

**Comment by mottosso** [comment]
UUIDs added, and serialisation takes these into account during collection and extraction.

I've also made it such that the rig maintains the original UUID from modeling, such that any shader associated with the original mesh retains its connection to the meshes in rigging. Only Ben has this currently, the others will in the future.

The next steps are..
1. Exporting shader groups
2. Along with their shaders
3. And the shader's connection
4. And finally connecting meshes with their shaders via their UUIDs.

Here's the serialisation format, same as I showed you before @BigRoy.

``` json
[
  {
    "name": "lightMetal_SG",
    "uuid": "f7b112ad-90bf-4274-8329-19a02092a083",
    "members": [
      {
        "name": "|:ben_GRP|:L_leg_GEO",
        "uuid": "53470dac-3709-499d-a490-4b8003b178ee",
        "properties": {
          "subdivision": 2,
          "displacementOffset": 0.94,
          "roundEdges": false,
          "objectId": "f35"
        }
      },
      {
        "name": "|:ben_GRP|:R_arm_GEO",
        "uuid": "8048064a-f6e0-48d4-bd03-e45b13dd2526"
      },
      {
        "name": "|:ben_GRP|:neck_GEO",
        "uuid": "53470dac-3709-499d-a490-4b8003b178ee"
      }
    ]
  },
  {
    "name": "orangeMetal_SG",
    "uuid": "f7b112ad-90bf-4274-8329-19a02092a083",
    "members": [
      {
        "name": "|:ben_GRP|:body_GEO.f[22:503]",
        "uuid": "8048064a-f6e0-48d4-bd03-e45b13dd2526"
      }
    ]
  }
]
```

**Comment by mottosso** [comment]
Merging and moving on

**Comment by BigRoy** [comment]
Just for completeness sake:

+1. Good steps forward.

**Pull request merged**
