### PR TITLE
Update for family 'model'

### PR DESCRIPTION
**Pull request by BigRoy**
**New plugins**:
- ValidatorMeshNonZeroFaceArea: Ensure no faces exists with a zero area size (up to tolerance)
- ValidatorMeshNonZeroEdges: Ensure no edges exists with a zero edge length (up to tolerance)

**Changes**:
- ValidateTransformFrozen: Implement tolerance to work around floating point precision errors.
- ValidateTransformNamingSuffix: Disable suffices `_GES` and `_GEP` for meshes.

### CODE REVIEW

**Comment by mottosso** [comment]
Cool, do these work with the model from The Deal?

**Comment by BigRoy** [comment]
> Cool, do these work with the model from The Deal?

Yes, they sure do!

**Comment by mottosso** [comment]
It's not working for me. :(

``` python
import pyblish.api
pyblish.api.discover()
```

This returns the Magenta plug-ins as I'd expect. But the model doesn't seem to get selected. What am I missing?

I also noticed the Magenta integration from my latest pull-request wasn't working, and that the model isn't in the /maya directory. Making a PR with a fix now.

**Comment by mottosso** [comment]
I accidentally pushed directly into the main repo, sorry about that. But maybe it simplifies things, if you rebase you should be getting a working version, and then maybe we can move the development files into `/maya`?

**Comment by BigRoy** [comment]
> This returns the Magenta plug-ins as I'd expect. But the model doesn't seem to get selected. What am I missing?

My local repository that is currently the same as this pull request is totally working fine. Am I missing something? Do you have both `pyblish_magenta` and `lucidity` available? And of course I assume you `dash`'ed your way into the model.

Assets don't have to be in a Maya folder (with the schema currently in The Deal) or are you referring to something else?

Or actually, it might not be triggering the `userSetup.py` on my end. Was the error in there?

**Comment by mottosso** [comment]
Yes, that's all set up right I think.

But I'm getting this.

image

> Assets don't have to be in a Maya folder (with the schema currently in The Deal) or are you referring to something else?

On second thought, let's save that for the forum, it's related to The Deal and not so much Magenta. It's about this: http://forums.pyblish.com/t/pyblish-magenta/79/80

**Comment by mottosso** [comment]
Or is it because of this exact change, of setting the Maya project to the development directory?

**Comment by BigRoy** [comment]
It was in the root comparison that I did in the Selector, not sure why it popped up just now for the first time. Anyway, I pushed some new updates to my repository that should fix it. Also merged with the latest 'master' branch `pyblish/pyblish-magenta`.

Do I have to do a new pull request and close this one?

**Comment by mottosso** [comment]
Cool, trying now.

No, the pull request will keep up to date with your fork, it will sync to the branch, in this case `master`.

**Comment by mottosso** [comment]
I'm not sure it's working still. Have you set your project to `thedeal` directory?

**Comment by mottosso** [comment]
It works if I set the project to `thedeal` directory, but that won't work very well with dash. :(

Could the Selector use the `PROJECTROOT` variable somehow?

This is what it has to play with.

``` yaml
        PROJECTSROOT: Absolute path to where projects are located
        PROJECTROOT: Absolute path to current project
        DEVELOPMENTDIR: Absolute path to current development directory
        PROJECT: Name of current project
        ASSET: Name of current asset
        FAMILY: Family of current asset
```

**Comment by BigRoy** [comment]
Ah wait, now I see what's going on. Sorry. You're totally right. Maya's project root directory is NOT the same as the real project's root directory because we're setting it per asset now.

The error checking that I did there was redundant. Or was actually checking whether Maya's project was actually set correctly for the asset.

Will fix!

**Comment by mottosso** [comment]
No worries, looks like we're at a crossroads.

We can either:
- Set the project dir to `thedeal`, in which case dash can still create the development dir, but the user will have to browse to it manually
- Set the project dir to the development dir, in which case the Selector needs to be adjusted

**Comment by BigRoy** [comment]
I'll adjust the Selector for now.

Somehow `pyblish_magenta` and `lucidity` can't be found when starting Maya through `dash`. Any idea why? Nevermind, rebooting seemed to solve it.

**Comment by BigRoy** [comment]
How about now?

_Note that this change with userSetup.py also automatically tries to make you work in a `maya` development folder, but there's no validator in place to ensure you're working there._

**Comment by mottosso** [comment]
Having a go.

**Comment by mottosso** [comment]
Flawless. :)

**Comment by mottosso** [comment]
When you're ready to merge, go ahead.

**Comment by mottosso** [comment]
Oh, but one thing.

**Comment by mottosso** [comment]
How about making the extractor optional, so I can test the validators?

**Comment by BigRoy** [comment]
Done.

Might be nice to allow running up to a certain order through the GUI easily? 
Maybe right click on the 'run' button to choose 'run up to Validators'?

**Comment by mottosso** [comment]
> Might be nice to allow running up to a certain order through the GUI easily? 
> Maybe right click on the 'run' button to choose 'run up to Validators'?

Better make it a feature request, either on the forum or as an issue.

**Comment by mottosso** [comment]
Merging this!

**Pull request merged**
